### ISSUE TITLE
Loki数据源

### ISSUE THREAD

**Issue by hedaweiii** [opsre/WatchAlert#106]
Loki作为数据源已经能正常产生告警吗？我查看我的Loki日志，确实是有查询日志的，但是我连一个告警demo都弄不出来。用同样的logql，去grafana查询，能查出来结果。我不知道到底是哪里不对，导致在最低条件下一条告警demo都没有。Prometheus 能够正常使用。
![image](https://github.com/user-attachments/assets/e7325f65-2b66-4d85-986e-2a1f213286b7)
![image](https://github.com/user-attachments/assets/6bd39482-a021-4e1d-9663-dfd500de8bbf)

**Comment by Cairry** [comment]
<img width="486" alt="image" src="https://github.com/user-attachments/assets/51102cf6-1ccb-4a71-acee-87f521a6f9ae" />
你这里怎么是空的。
案例：
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/559f3792-3417-4905-ad91-8ad228075070" />

**Comment by hedaweiii** [comment]
> <img alt="image" width="486" src="https://private-user-images.githubusercontent.com/115769353/398909247-51102cf6-1ccb-4a71-acee-87f521a6f9ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTM1MzMsIm5iZiI6MTczNTI5MzIzMywicGF0aCI6Ii8xMTU3NjkzNTMvMzk4OTA5MjQ3LTUxMTAyY2Y2LTFjY2ItNGE3MS1hY2VlLTg3ZjUyMWE2ZjlhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwOTUzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTk0NTgxMjcwMjQ4OGYxZDFlZDIwOGM5MzE3MjNjYzIxZGRhZWQ2ZGMxNzlmN2YzY2QzN2MxZjEyYjU5ZDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zydEwWnXJZ1-Krmg_j1y8RrbkoL-H9ZrxCjqJZ8GNGg"> 你这里怎么是空的。 案例： <img alt="image" width="1150" src="https://private-user-images.githubusercontent.com/115769353/398909828-559f3792-3417-4905-ad91-8ad228075070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTM1MzMsIm5iZiI6MTczNTI5MzIzMywicGF0aCI6Ii8xMTU3NjkzNTMvMzk4OTA5ODI4LTU1OWYzNzkyLTM0MTctNDkwNS1hZDkxLThhZDIyODA3NTA3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwOTUzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDU5OWVhZDEyNmIwNWYyMjBmODllYmQzN2VhMzVmMTc3N2RkNTUyZjFjYjFmZTE3MjZmYjA4ODJhNzJmY2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BstHCLC6DNpu_dhk_Ofsn7aV5vH1i7pl0upOwNMlJEQ">

我曾尝试过这样做，没有效果才置空的

**Comment by hedaweiii** [comment]
> <img alt="image" width="486" src="https://private-user-images.githubusercontent.com/115769353/398909247-51102cf6-1ccb-4a71-acee-87f521a6f9ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTM1MzMsIm5iZiI6MTczNTI5MzIzMywicGF0aCI6Ii8xMTU3NjkzNTMvMzk4OTA5MjQ3LTUxMTAyY2Y2LTFjY2ItNGE3MS1hY2VlLTg3ZjUyMWE2ZjlhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwOTUzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTk0NTgxMjcwMjQ4OGYxZDFlZDIwOGM5MzE3MjNjYzIxZGRhZWQ2ZGMxNzlmN2YzY2QzN2MxZjEyYjU5ZDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zydEwWnXJZ1-Krmg_j1y8RrbkoL-H9ZrxCjqJZ8GNGg"> 你这里怎么是空的。 案例： <img alt="image" width="1150" src="https://private-user-images.githubusercontent.com/115769353/398909828-559f3792-3417-4905-ad91-8ad228075070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyOTM1MzMsIm5iZiI6MTczNTI5MzIzMywicGF0aCI6Ii8xMTU3NjkzNTMvMzk4OTA5ODI4LTU1OWYzNzkyLTM0MTctNDkwNS1hZDkxLThhZDIyODA3NTA3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwOTUzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDU5OWVhZDEyNmIwNWYyMjBmODllYmQzN2VhMzVmMTc3N2RkNTUyZjFjYjFmZTE3MjZmYjA4ODJhNzJmY2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BstHCLC6DNpu_dhk_Ofsn7aV5vH1i7pl0upOwNMlJEQ">

抱歉，已经可以了。打扰了，感谢大佬。
